problem = "tcp"

[rooms]
output = "output"
reader = "tcp-fan-reader"
sink = "tcp-fan-probe-sink"
source = "tcp-fan-probe-source"

[[pipes]]
from = "reader.output"
to = "output.feed"
min = 2
max = 40

[[pipes]]
from = "reader.feedback"
to = "sink.in"
min = 2
max = 40

[[pipes]]
from = "source.slot0"
to = "reader.slot0"
min = 2
max = 40

[[pipes]]
from = "source.slot1"
to = "reader.slot1"
min = 2
max = 40

[[pipes]]
from = "source.slot2"
to = "reader.slot2"
min = 2
max = 40

[[pipes]]
from = "source.slot3"
to = "reader.slot3"
min = 2
max = 40

[[pipes]]
from = "source.slot4"
to = "reader.slot4"
min = 2
max = 40

[[pipes]]
from = "source.slot5"
to = "reader.slot5"
min = 2
max = 40

[[pipes]]
from = "source.slot6"
to = "reader.slot6"
min = 2
max = 40

[[pipes]]
from = "source.slot7"
to = "reader.slot7"
min = 2
max = 40

[[pipes]]
from = "source.slot8"
to = "reader.slot8"
min = 2
max = 40

[[pipes]]
from = "source.slot9"
to = "reader.slot9"
min = 2
max = 40

[[pipes]]
from = "source.slot10"
to = "reader.slot10"
min = 2
max = 40

[[pipes]]
from = "source.slot11"
to = "reader.slot11"
min = 2
max = 40

[[pipes]]
from = "source.slot12"
to = "reader.slot12"
min = 2
max = 40

[[pipes]]
from = "source.slot13"
to = "reader.slot13"
min = 2
max = 40

[[pipes]]
from = "source.slot14"
to = "reader.slot14"
min = 2
max = 40

[[pipes]]
from = "source.slot15"
to = "reader.slot15"
min = 2
max = 40
