problem = "memory"

[rooms]
input = "input"
output = "output"
gate = "memory-select-gate"
select = "memory-select-zero"
reduce = "memory-reduce"
leaf0 = "memory-select-leaf"
leaf1 = "memory-select-leaf"

[[pipes]]
from = "input.out"
to = "gate.raw"
[[pipes]]
from = "gate.request"
to = "select.request"
[[pipes]]
from = "select.child0"
to = "leaf0.request"
[[pipes]]
from = "select.child1"
to = "leaf1.request"
[[pipes]]
from = "leaf0.response"
to = "reduce.child0"
[[pipes]]
from = "leaf1.response"
to = "reduce.child1"
[[pipes]]
from = "reduce.response"
to = "gate.result"
[[pipes]]
from = "gate.output"
to = "output.feed"
