problem = "memory"

[rooms]
input = "input"
output = "output"
dec = "memory-tree-decoder"
leaf0 = "memory-tree-echo"
leaf1 = "memory-tree-echo"

[[pipes]]
from = "input.out"
to = "dec.parent_req"
[[pipes]]
from = "dec.child_req0"
to = "leaf0.request"
[[pipes]]
from = "leaf0.response"
to = "dec.child_resp0"
[[pipes]]
from = "dec.child_req1"
to = "leaf1.request"
[[pipes]]
from = "leaf1.response"
to = "dec.child_resp1"
[[pipes]]
from = "dec.parent_resp"
to = "output.feed"
